## Numpy in Python

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy 
arr = numpy.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)

2.0.2


In [5]:
# type()
import numpy as np

arr = np.array([2,4,6,8,10])
print(arr)
print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [12]:
# 0-D Array
a = np.array(10) # OD array
b = np.array([1,2,3]) # 1D array
result = a + b
print(result)
print(a.ndim)
print(b.ndim)

[11 12 13]
0
1


In [13]:
# 1-D Array
arr = np.array([2,3,46,7,8])
print(arr)
print(arr.ndim)

[ 2  3 46  7  8]
1


In [14]:
# 2-D Array
arr = np.array([[2,4,6],[5,6,8]])
print(arr)
print(arr.ndim)

[[2 4 6]
 [5 6 8]]
2


In [15]:
# 3-D Array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,6,8]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 6 8]]]
3


In [18]:
# Higher Dimensional Array
arr = np.array([2,6,8,9],ndmin=10)
print(arr)
print('Number of dimensions: ',arr.ndim)

[[[[[[[[[[2 6 8 9]]]]]]]]]]
Number of dimensions:  10


## Indexing of numpy array

In [22]:
# 1-D Array Accessing
arr = np.array([2,5,6,8])
print(arr[1])
print(arr[2]+arr[3])

5
14


In [ ]:
# 2-D Array Accessing
arr = np.array([[2,4,6,7],[2,7,9,3]])
print(arr[1,3])


3


In [28]:
# 3-D Array Accessing
arr = np.array([[[1,2,3],[5,7,9]],[[2,6,4,],[10,32,45]]])
print(arr[1,1,1])
print(arr[-2,-2,-2])

32
2


In [27]:
## Negative Indexing
arr = np.array([[2,4,5,6,7],[1,2,6,8,4]])
print(arr[-2,-2])

6
