## Slicing

In [1]:
# start:End
import numpy as np

arr = np.array([2,3,5,6,8,9])
print(arr[1:5])

[3 5 6 8]


In [2]:
# start: 
arr = np.array([3,6,8,1,4,7])
print(arr[3:])

[1 4 7]


In [3]:
# :end
arr = np.array([4,2,7,9,1,3])
print(arr[:4])

[4 2 7 9]


In [4]:
# Negative slicing
arr = np.array([2,5,4,7,9,0,1,3])
print(arr[-4:-1])

[9 0 1]


In [8]:
# Step 
arr = np.array([2,4,5,8,9,0,1])
print(arr[::3])

[2 8 1]


In [9]:
# 3-D Array Slicing
arr = np.array([
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]],

    [[13,14,15,16],
     [17,18,19,20],
     [21,22,23,24]]
])

print(arr[0:2,1:3,1:3])

[[[ 6  7]
  [10 11]]

 [[18 19]
  [22 23]]]


## Array Data Type

In [10]:
arr = np.array([2,4,6,8])
print(arr.dtype)

int64


In [11]:
arr = np.array([2.4,1.2,3.5,6.2,7.6])
print(arr.dtype)

float64


In [12]:
arr = np.array([2,4,6,8],dtype='S')
print(arr)
print(arr.dtype)

[b'2' b'4' b'6' b'8']
|S1


In [14]:
arr = np.array([2,4,6,8],dtype='i')
print(arr.dtype)

int32


In [16]:
c = np.array(['hello','world'],dtype='U')
print(c.dtype)

<U5


In [17]:
d = np.array([{'x':1},[1,2,3]], dtype='O')
print(d.dtype)

object


In [18]:
arr = np.array([2,4,5,7,8],dtype='i4')
print(arr)
print(arr.dtype)

[2 4 5 7 8]
int32


In [20]:
# Converting the data types
arr = np.array([1.2,3.4,5.6,7.8,3.2]) 
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)

[1 3 5 7 3]
int64


In [22]:
arr = np.array([1,1.2,"Hello",True])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True  True]
bool
