### Numpy - Copy and View

In [1]:
# Copy()

import numpy as np
arr = np.array([2,4,5,6,3])
x = arr.copy()

arr[1] = 100

print("Original array: ",arr)
print("Copied array: ",x)

Original array:  [  2 100   5   6   3]
Copied array:  [2 4 5 6 3]


In [3]:
# View()

arr = np.array([1,3,4,5,7])
x = arr.view()
arr[1] = 50

print("Original array: ",arr)
print("View array: ",x)

print("Does arr own its Data?",arr.base is None)
print("Does x own its data?",x.base is None)

Original array:  [ 1 50  4  5  7]
View array:  [ 1 50  4  5  7]
Does arr own its Data? True
Does x own its data? False


In [4]:
# Check if Array Owns its Data

arr = np.array([2,3,4,6,8,9])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[2 3 4 6 8 9]


## Shaping of the array

In [6]:
arr = np.array([4,7,9,3],ndmin=5)
print(arr)
print("Shape of array: ",arr.shape)

[[[[[4 7 9 3]]]]]
Shape of array:  (1, 1, 1, 1, 4)


In [7]:
# Reshaping of the array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)
print("Original array: ",arr)
print("Reshaped array:\n",newarr)

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,2)
print("Original array: ",arr)
print("Reshaped array:\n",newarr)

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
## Flattened the array

arr = np.array([[2,3,4,5],[4,6,8,2]])

arr1= arr.reshape(-1)

print(arr)
print(arr1)
print(arr.dtype)

[[2 3 4 5]
 [4 6 8 2]]
[2 3 4 5 4 6 8 2]
int64


## Iterating of array


In [12]:
arr = np.array([3,4,6,8,9,1])

for x in arr:
    print(x)

3
4
6
8
9
1


In [13]:
# 2-D array

arr = np.array([[2,4,3,7],[1,4,7,8]])

for x in arr:
    print(x)

[2 4 3 7]
[1 4 7 8]


In [14]:
# 3-D Array

arr = np.array([
    [[2,4,6,8],[1,3,7,0]],
    [[1,3,6,4],[2,5,8,9]]
])

for x in arr:
    print(x)

[[2 4 6 8]
 [1 3 7 0]]
[[1 3 6 4]
 [2 5 8 9]]


In [15]:
arr = np.array([[2,4,1,5],[5,4,8,7]])

for x in np.nditer(arr[:,::2]):
    print(x)

2
1
5
8


In [17]:
## Enumerated Iteration

arr = np.array([2,4,6,9,1])

for idx, x in np.ndenumerate(arr[1:4:2]):
    print(idx,x)

(0,) 4
(1,) 9


In [18]:
arr = np.array([[2,3,4],[2,1,4],[5,7,9]])

for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 2
(1, 1) 1
(1, 2) 4
(2, 0) 5
(2, 1) 7
(2, 2) 9
