## Joining the numpy array

In [1]:
# 1-d Array
import numpy as np

arr1 = np.array([2,4,6,8])
arr2 = np.array([4,6,8,0])

arr = np.concatenate((arr1, arr2))
print(arr)

[2 4 6 8 4 6 8 0]


In [5]:
# 2-D Array
arr1 = np.array([[2,5],[7,8]])
arr2 = np.array([[4,9],[1,3]])

arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[2 5 4 9]
 [7 8 1 3]]


In [ ]:
## Using Stack 
arr1 = np.array([2,3,5])
arr2 = np.array([4,6,8])
arr = np.stack((arr1,arr2), axis=0) # row wise 
print(arr)

[[2 3 5]
 [4 6 8]]


In [ ]:
arr1 = np.array([2,4,6])
arr2 = np.array([5,7,9])
arr = np.stack((arr1,arr2), axis=1) # Column wise
print(arr)

[[2 5]
 [4 7]
 [6 9]]


In [11]:
# hstack()
arr1 = np.array([3,5,7,8])
arr2 = np.array([2,6,9,5])

arr = np.hstack((arr1,arr2))
print(arr)

[3 5 7 8 2 6 9 5]


In [12]:
# vstack()
arr1 = np.array([2,4,7,9])
arr2 = np.array([4,6,9,0])

arr = np.vstack((arr1,arr2))
print(arr)

[[2 4 7 9]
 [4 6 9 0]]


In [13]:
# dstack()
arr1 = np.array([2,4,6])
arr2 = np.array([1,3,5])

arr = np.dstack((arr1,arr2))
print(arr)

[[[2 1]
  [4 3]
  [6 5]]]


## Spliting Array

In [ ]:
arr = np.array([2,3,5,7,8,9])
newarr = np.array_split(arr, 4)
print(newarr)

[array([2, 3]), array([5, 7]), array([8]), array([9])]


In [16]:
print(newarr[1])

[5 7]


In [20]:
## Spliting in 2D Array

arr = np.array([[2,3,4],[4,5,7],[6,8,0],[2,4,6]])

newarr = np.array_split(arr,3)
print(newarr)

[array([[2, 3, 4],
       [4, 5, 7]]), array([[6, 8, 0]]), array([[2, 4, 6]])]


In [25]:
# Split 2-D array in Column wise
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Searching array

In [29]:
arr = np.array([2,3,5,7,9,5])
x = np.where(arr == 9)
print(x)

(array([4]),)


In [30]:
arr = np.array([1,3,4,6,9,2])
x = np.where(arr % 2 == 0)
print(x)

(array([2, 3, 5]),)


In [31]:
arr = np.array([1,3,4,6,9,2])
x = np.where(arr % 2 == 1)
print(x)

(array([0, 1, 4]),)


In [ ]:
# searchsorted()

arr = np.array([2,8,3,9,1]) # 2,8,3,9,1 =>
                         # 2,3,8,9,1
                         # 2,3,8,1,9
                         # 2,3,1,8,9
                         # 2,1,3,8,9
                         # 1,2,3,8,9
x = np.searchsorted(arr, 9)
print(x)

5


In [ ]:
# search for multiple values
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


In [ ]:
# from right side
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6], side='right')
print(x)

[1 2 3]


In [ ]:
# Multiple Values
arr = np.array([7,3,1,5])
sorted_arr = np.sort(arr)
x = np.searchsorted(sorted_arr, [2,4,6])
print(x)
print(sorted_arr)

[1 2 3]
[1 3 5 7]
