## Sorting numpy array

In [1]:
import numpy as np

arr = np.array([7,6,2,0,1])
print(np.sort(arr))

[0 1 2 6 7]


In [2]:
arr = np.array(["orange","banana","apple","cherry"])
print(np.sort(arr))

['apple' 'banana' 'cherry' 'orange']


In [3]:
arr = np.array([True,False,True,False,True])
print(np.sort(arr))

[False False  True  True  True]


In [4]:
## 2-D Array
arr = np.array([[6,3,0],[1,9,4]])
print(np.sort(arr))

[[0 3 6]
 [1 4 9]]


In [5]:
## 3-D Array
arr = np.array([[[2,3,0]],[[9,2,1]]])
print(np.sort(arr))

[[[0 2 3]]

 [[1 2 9]]]


### Filter the array

In [7]:
## Filter the array
arr = np.array([23,67,1,89,56])
x = [False,True,False,True,True]

newarr = arr[x]
print(newarr)

[67 89 56]


In [8]:
filter_arr = arr > 50
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True  True]
[67 89 56]


In [10]:
filter_arr = arr%2 == 1
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[ True  True  True  True False]
[23 67  1 89]


## Rondom Number in numpy

In [20]:
import numpy as np

print(np.random.randint(0,101))

57


In [41]:
from numpy import random

x = random.randint(100)
print(x)

69


In [61]:
x = random.rand()
print(x)

0.4722994420817892


In [70]:
# Generating random 1-D array
x = random.randint(150,size=(6))
print(x)

[138  56  60 145 102  32]


In [74]:
# 2-D array random 
x = random.randint(200, size=(4,5))
print(x)

[[194   9 116  49 193]
 [120 102  89 187 167]
 [ 35 165 112 144 141]
 [ 85  63  70 199 115]]


In [81]:
# 3-D array random
x = random.randint(51,size=(3,4,5))
print(x)

[[[ 7 12  9 35  6]
  [23 17 16 22 48]
  [ 4 33 36 15 49]
  [34 48 50 22  1]]

 [[ 4 27 22 45 17]
  [17 11 49  5  1]
  [16 38 43 25  8]
  [ 5 19  8 16 50]]

 [[ 0 28 18 37 20]
  [ 5 38 46 33 11]
  [50 23 34 21  1]
  [49 10 39 44 25]]]


In [78]:
# float value
x = random.rand(10)
print(x)

[0.91513057 0.81341082 0.44533265 0.41750684 0.06750374 0.42862331
 0.92649967 0.35504128 0.29928454 0.07709184]


In [79]:
x = random.rand(2,4)
print(x)

[[0.00106877 0.40699645 0.39129947 0.51641537]
 [0.32875459 0.899328   0.27199223 0.81593661]]


In [80]:
x = random.rand(2,3,4)
print(x)

[[[0.42082674 0.56397453 0.34224768 0.3222122 ]
  [0.50816329 0.907806   0.81871944 0.53515526]
  [0.88171196 0.37731111 0.02078305 0.71510854]]

 [[0.91811927 0.48630255 0.0401001  0.61863027]
  [0.7406532  0.30948698 0.63344924 0.64480179]
  [0.97759988 0.83487822 0.6354771  0.19364867]]]


In [ ]:
# Choice()
# 1-D array
x = random.choice([3,6,2,5,9])
print(x)

3


In [107]:
# 2-D array
x = random.choice([2,5,7,4,8,9], size=(3,4))
print(x)

[[8 2 7 9]
 [2 9 5 8]
 [2 8 7 8]]


In [109]:
# 3-D array
x = random.choice([3,5,7,1,8],size=(2,3,4))
print(x)

[[[8 1 1 1]
  [3 1 7 8]
  [7 7 1 1]]

 [[7 5 1 3]
  [1 1 1 8]
  [1 7 3 3]]]


In [113]:
# choice() with probability
x = random.choice([2,4,7,9],size=100, p=[0.1,0.3,0.6,0.0])
print(x)

[7 4 2 4 7 4 4 4 7 7 4 7 2 7 7 7 4 2 7 7 2 4 7 7 7 7 7 7 4 7 7 7 7 7 4 7 7
 7 4 7 2 4 2 4 7 7 7 7 4 7 7 4 7 2 7 7 7 7 7 7 7 4 4 4 4 7 7 7 4 4 4 4 7 7
 2 7 7 7 7 7 7 7 7 7 7 7 4 7 2 4 4 2 7 7 7 7 4 2 7 7]


In [139]:
# 2-D Array
x = random.choice([3,5,2,7],size=(3,4),p=[0.3,0.5,0.0,0.2])
print(x)

[[3 3 3 3]
 [3 3 7 3]
 [5 5 3 5]]


## Random Permutations with numpy

In [157]:
# shuffle()
arr = [2,4,6,8,3]
random.shuffle(arr)
print(arr)

[8, 2, 4, 6, 3]


In [150]:
# permutation()
arr = [2,4,6,8,3]
x = random.permutation(arr)

print("Original: ",arr)
print("Shuffled Copy: ",x)

Original:  [2, 4, 6, 8, 3]
Shuffled Copy:  [2 8 6 3 4]
